version: '3'

services:
  api:
    build: ./api
    ports:
      - "${API_PORT}:5000"
  web:
    environment:
      - API_URL
    build: ./web
    ports:
      - '${WEB_PORT}:8080'
    volumes:
      - './web:/app'
